# Site
repository: BaekJaeIn/BaekJaeIn.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 백재인
title: Web developer
email: jiback96@naver.com
website: github.com/BaekJaeIn/BaekJaeIn.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username: BaekJaeIn
# stackoverflow_username: "00000001"
# facebook_username: Jaein1005
# instagram_username: ji___100
# linkedin_username: jameswgrant
# youtube_username: @jaein1005

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. 5년차 개발자 백재인입니다. 

  현재 한진정보통신에서 대한항공 홈페이지 운영팀의 일원으로, 대한항공 홈페이지 중 컨텐츠 영역의 운영과 개선을 담당하고 있습니다. 새로운 환경과 기술에 대한 도전을 두려워하지 않으며, 업무 전반에 걸쳐 주도적으로 문제를 해결하고 개선하는 경험을 쌓아왔습니다.

  저는 커리어의 가장 중요한 가치로 성장을 꼽습니다. 첫 취업부터 지금까지의 모든 선택은 스스로를 더 크게 성장시키기 위한 방향이었으며, 그 과정에서 쉽게 얻을 수 없는 소중한 경험들을 축적해왔습니다.

  새로운 도전은 성공이든 실패든 반드시 저를 한 단계 더 높여준다고 믿습니다. 이러한 신념을 바탕으로, 앞으로도 변화를 두려워하지 않고 열정적으로 업무에 임할 준비가 되어 있습니다.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left top-middle #left top-middle
        title: 에버에듀시스템
        sub_title: 목포과학대학교 Life 사업단 성인학습자 이력관리 시스템 구축
        # link: github.com/sproogen
        # link_text: Project Website
        caption: 2020.07. ~ 2021.09.<br> 2022.07. ~ 2022.08.
        quote: >
          <mark>Java</mark>
          <mark>nexacro17</mark>
          <mark>tibero6</mark>
          <mark>eclipse</mark>
          <mark>svn</mark>
          <mark>tomcat</mark>
          <mark>spring</mark>
        description: | # this will include new lines to allow paragraphs
          - 학적, 수업, 등록, 장학, 교직원 파트 담당 개발

      - layout: left #left top-middle
        title: 에버에듀시스템
        sub_title: SH공사 전사자원통합관리시스템 구축 1단계
        caption: 2021.09. ~ 2022.07.
        quote: >
          <mark>Java</mark>
          <mark>Websqure</mark>
          <mark>oracle11g</mark>
          <mark>eclipse</mark>
          <mark>svn</mark>
          <mark>spring</mark>
        description: | # this will include new lines to allow paragraphs
          - 인사기본사항, 인사발령 담당 개발
          - 리눅스 crontab기반 배치프로그램 개발
          - 사용자 입력 레포트 개발(전자 근로계약서)
          - 오라클 프로시저 개발

      - layout: left #left top-middle
        title: 에버에듀시스템
        sub_title: 경희대학교 학사관리시스템 운영
        caption: 2022.09. ~ 2023.06.
        quote: >
          <mark>Java</mark>
          <mark>nexacro14</mark>
          <mark>tibero6</mark>
          <mark>eclipse</mark>
          <mark>jennifer</mark>
          <mark>spring</mark>
        description: | # this will include new lines to allow paragraphs
          - 대학원입시, 취업, 동문, 교직, 학생, 공용장비 파트 담당 운영
          - 수업, 성적, 수강신청 서브 운영
          - 마이크로디그리(MD) 협약에 따른 신규 개발

      - layout: left #left top-middle
        title: 한진정보통신
        sub_title: 대한항공 홈페이지 콘텐츠 개편
        caption: 2023.08. ~ 2024.06
        quote: >
          <mark>Java</mark>
          <mark>AEMaaCS</mark>
          <mark>HTL</mark>
          <mark>jsp</mark>
          <mark>nextjs</mark>
          <mark>react</mark>
          <mark>Jenkins</mark>
          <mark>Bicbucket</mark>
          <mark>Jira</mark>
          <mark>sling</mark>
          <mark>JCR SQL2</mark>
          <mark>WebComponent</mark>
          <mark>Stencil.js</mark>
        description: | # this will include new lines to allow paragraphs
          - On-premise AEM 시스템을 Cloud AEM 시스템으로 전환
          - Headless AEM, Remote SPA Frontend, Micro Frontend 신규 도입
          - 개편 대상 신규 컴포넌트 개발 
          - 개편 대상이 아닌 legacy 컴포넌트 migration
          - 이벤트 응모 기능 migration 및 수정

      - layout: left #left top-middle
        title: 한진정보통신
        sub_title: 대한항공 홈페이지 운영
        caption: 2023.06. ~
        quote: >
          <mark>Java</mark>
          <mark>AEMaaCS</mark>
          <mark>HTL</mark>
          <mark>jsp</mark>
          <mark>nextjs</mark>
          <mark>react</mark>
          <mark>Jenkins</mark>
          <mark>Bicbucket</mark>
          <mark>Jira</mark>
          <mark>sling</mark>
          <mark>JCR SQL2</mark>
          <mark>WebComponent</mark>
          <mark>Stencil.js</mark>
        description: | # this will include new lines to allow paragraphs
          - 이벤트 응모 기능 개발 및 데이터 전송
          - 웹 접근성(W3C)기준 준수
          - 카카오톡학생증 연계 프로모션 기능 개발
          - 카카오모빌리티 연계 프로모션 기능 개발
          - 이벤트 응모 프로세스 개선
          - 대한항공 New CI 프로젝트 (~ 2025.03)
          - 대한항공 ECC 페이지 개편 프로젝트 (~ 2025.03)
          - 대한항공 홈페이지 신규 기능 소개 페이지 개발 프로젝트 (~ 2025.08)
          - 대한항공 라운지 소개 페이지 개편 프로젝트 (~ 2025.12)
          - 통합검색 표출 내용 개선 (~ 2025.12)
          - 이벤트 페이지 및 Asset 최적화 (~ 2026.01)
          - 대한항공 홈페이지 AI 번역 프로젝트 (~ 2026.01)
          - 항공기안내 페이지 AEM Universal Editor 적용 (~ 2026)
          - 컨텐츠 페이지 디자인 시스템 적용 (~ 2026)
          - AI UX 라이팅 (~ 2026)

  - title: Experience # Title for the section
    layout: layout2 # Type of content section (list/text)
    content:
      - title_1: (주)에버에듀시스템
        link_1: http://www.averedusystem.com
        link_text_1: averedusystem.com
        sub_title_1: 웹 개발자
        caption_1: 2020.08. ~ 2023.06.
        title_2: 한진정보통신(주)
        link_2: https://www.hist.co.kr
        link_text_2: hist.co.kr
        sub_title_2: AEM 개발자
        caption_2: 2023.06. ~

  - title: Education # Title for the section
    layout: layout3 # Type of content section (list/text)
    content:
      - title_1: 동양고등학교
        caption_1: 2012.03. ~ 2015.02.
        title_2: 명지전문대학교
        sub_title_2: 정보통신공학과
        caption_2: 2015.03. ~ 2020.02.
        sub_caption_2: 학점 3.5
        title_3: 학점은행제
        sub_title_3: 정보통신공학과
        caption_3: 2021.07. ~ 2022.02.
        sub_caption_3: 학점 4.19

  - title: Certificate # Title for the section
    layout: layout4 # Type of content section (list/text)
    content:
      - title_1: 정보처리기사
        sub_title_1: 한국산업인력공단
        caption_1: 2021.11.
        title_2: AWS Certified Developer
        sub_title_2: AWS
        caption_2: 2023.08.
        title_3: 데이터분석준전문가
        sub_title_3: 데이터자격검정
        caption_3: 2024.11.
        title_4: TOEIC
        sub_title_4: ETS
        caption_4: 2025.09.
        sub_caption_4: 780

  - title: A Little More About Me
    layout: text
    content:
      - caption: 끊임없는 도전과 발전
        content: | # this will include new lines to allow paragraphs
          저는 목표를 설정하면 반드시 이루기 위해 끊임없이 도전하고 실행하는 개발자입니다. 실행 없는 도전은 결과를 만들 수 없다고 믿기에, 어떤 어려움 앞에서도 끝까지 해내려는 끈기를 가지고 업무에 임해왔습니다. “어려워도 계속 해보자”는 태도는 저의 가장 큰 강점이자 신조입니다.

          군 복무 시절, 저는 견인포병으로 근무하며 제가 운용하던 포에 흥미를 갖게 되었고, 자연스럽게 군단 포병 전체가 참여하는 포반장학교에서 1등을 하겠다는 목표를 세웠습니다. 군 환경에서 학습하기가 쉽지 않았지만, 개인정비 시간과 연등 시간을 활용해 매일 새벽 1시까지 두 달 동안 집중적으로 학습했습니다. 그 결과 포반장학교에서 최종 1등을 달성하며 노력의 가치를 다시 한 번 확인할 수 있었습니다.

          프로그래밍 역시 마찬가지라고 생각합니다. 기계를 이해하고 다루는 일은 쉽지 않고, 모든 언어가 영어 기반이다 보니 늘 새로운 장벽이 나타납니다. 그러나 저는 이런 장벽 앞에서 포기하지 않고, 끈기 있는 학습과 반복을 통해 끝내 해결해내며 성장해 왔습니다. 앞으로도 도전과 발전을 멈추지 않는 개발자로서 계속해서 높은 목표를 향해 나아가고자 합니다.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
